/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 26-янв-2023 12:14:19 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS dictionary.bic CASCADE
;

DROP TABLE IF EXISTS dictionary.bic_account CASCADE
;

DROP TABLE IF EXISTS dictionary.bic_account_regulation_type CASCADE
;

DROP TABLE IF EXISTS dictionary.bic_participant_type CASCADE
;

/* Drop Sequences */

DROP SEQUENCE  IF EXISTS  dictionary.bic_account_bic_account_id_seq  CASCADE
;

/* Create Sequences */

CREATE SEQUENCE dictionary.bic_account_bic_account_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;


/* Create Tables */

CREATE TABLE dictionary.bic
(
	bic_code varchar(9) NOT NULL,	-- БИК
	is_active integer NOT NULL   DEFAULT 1,	-- Статус актуальности данной записи
	business_day date NULL,	-- Дата ОД, к которой относятся данные Справочника БИК | фактически дата последнего обновления
	version integer NULL,	--  Номер версии Справочника БИК в течение операционного дня
	participant_name varchar(160) NULL,	--  Наименование участника
	country_code varchar(3) NULL,	-- Код страны
	region_code integer NULL,	-- Код территории
	date_in date NULL,	-- Дата включения в состав участников перевода
	date_out date NULL,	-- Дата исключения информации об участнике
	participant_type_id integer NULL,	-- Тип участника перевода
	transfer_service integer NULL,	-- Доступные сервисы перевода денежных средств
	registration_number varchar(9) NULL,	--  Регистрационный порядковый номер
	parent_bic varchar(9) NULL,	-- БИК головной организации
	english_name varchar(140) NULL,	-- Наименование участника на английском языке
	restriction_code varchar(4) NULL,	-- Код ограничения, наложенного на участника | В соответствии с ED807 к одному БИК может быть несколько ограничений 
	restriction_date date NULL,	-- Дата начала действия ограничения участника | В соответствии с ED807 к одному БИК может быть несколько ограничений
	swift_bic varchar(11) NULL,	-- БИК (СВИФТ) | по справочнику СВИФТ, стандарт ИСО 9362
	default_swift_bic integer NULL,	-- Признак использования БИК (СВИФТ), «по умолчанию»
	successor_bic varchar(9) NULL,	-- БИК преемника | В соответствии с ED807 поле атрибут вводится при установке ограничения на счет (таблица bic_account)
	locality_type varchar(5) NULL,	-- Тип населенного пункта | г.
	locality_name varchar(25) NULL	-- Наименование населенного пункта | Тверь
)
;

CREATE TABLE dictionary.bic_account
(
	bic_code varchar(9) NOT NULL,	-- БИК
	account varchar(20) NOT NULL,	-- Номер счета
	regulation_type varchar(4) NULL,	-- Тип счета в соответствии с нормативом
	cbr_bic varchar(9) NULL,	-- БИК ПБР, обслуживающего счет участника перевода
	date_in date NULL,	-- Дата открытия счета
	date_out date NULL,	-- Дата исключения информации о счете участника
	restriction_code varchar(4) NULL,	-- Код ограничения операций по счету | в соответствии с ED807 к одному счету может быть несколько ограничений
	restriction_date date NULL,	-- Дата начала действия Ограничения операций по счету | в соответствии с ED807 к одному счету может быть несколько ограничений
	is_active integer NOT NULL,	-- Статус актуальности данной записи
	status varchar(4) NULL	-- Статус счета из ED | ACAC
)
;

CREATE TABLE dictionary.bic_account_regulation_type
(
	regulation_type_id char(4) NOT NULL,	-- ID типа счета в соответствии с нормативом 
	name varchar(100) NULL	-- Наименование типа счета в соответствии с нормативом 
)
;

CREATE TABLE dictionary.bic_participant_type
(
	participant_type_id integer NOT NULL,	-- ID типа участника перевода
	name varchar(100) NULL	-- Наименование типа участника перевода
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE dictionary.bic ADD CONSTRAINT pk_dictionary_bic
	PRIMARY KEY (bic_code)
;

CREATE INDEX ixfk_dictionary_bic_transfer_participant_type ON dictionary.bic (participant_type_id ASC)
;

ALTER TABLE dictionary.bic_account ADD CONSTRAINT pk_dictionary_bic_account
	PRIMARY KEY (bic_code,account)
;

CREATE INDEX ixfk_dictionary_bic_account_bic_account_type ON dictionary.bic_account (regulation_type ASC)
;

ALTER TABLE dictionary.bic_account_regulation_type ADD CONSTRAINT pk_dictionary_bic_account_regulation_type
	PRIMARY KEY (regulation_type_id)
;

ALTER TABLE dictionary.bic_participant_type ADD CONSTRAINT pk_dictionary_bic_participant_type
	PRIMARY KEY (participant_type_id)
;

/* Create Foreign Key Constraints */

ALTER TABLE dictionary.bic ADD CONSTRAINT fk_dictionary_bic_participant_type_bic
	FOREIGN KEY (participant_type_id) REFERENCES dictionary.bic_participant_type (participant_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.bic_account ADD CONSTRAINT fk_dictionary_bic_account_bic_account_type
	FOREIGN KEY (regulation_type) REFERENCES dictionary.bic_account_regulation_type (regulation_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.bic_account ADD CONSTRAINT fk_dictionary_bic_account_bic
	FOREIGN KEY (bic_code) REFERENCES dictionary.bic (bic_code) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE dictionary.bic
	IS 'Справочник БИК'
;

COMMENT ON COLUMN dictionary.bic.bic_code
	IS 'БИК'
;

COMMENT ON COLUMN dictionary.bic.is_active
	IS 'Статус актуальности данной записи'
;

COMMENT ON COLUMN dictionary.bic.business_day
	IS 'Дата ОД, к которой относятся данные Справочника БИК | фактически дата последнего обновления'
;

COMMENT ON COLUMN dictionary.bic.version
	IS ' Номер версии Справочника БИК в течение операционного дня'
;

COMMENT ON COLUMN dictionary.bic.participant_name
	IS ' Наименование участника'
;

COMMENT ON COLUMN dictionary.bic.country_code
	IS 'Код страны'
;

COMMENT ON COLUMN dictionary.bic.region_code
	IS 'Код территории'
;

COMMENT ON COLUMN dictionary.bic.date_in
	IS 'Дата включения в состав участников перевода'
;

COMMENT ON COLUMN dictionary.bic.date_out
	IS 'Дата исключения информации об участнике'
;

COMMENT ON COLUMN dictionary.bic.participant_type_id
	IS 'Тип участника перевода'
;

COMMENT ON COLUMN dictionary.bic.transfer_service
	IS 'Доступные сервисы перевода денежных средств'
;

COMMENT ON COLUMN dictionary.bic.registration_number
	IS ' Регистрационный порядковый номер'
;

COMMENT ON COLUMN dictionary.bic.parent_bic
	IS 'БИК головной организации'
;

COMMENT ON COLUMN dictionary.bic.english_name
	IS 'Наименование участника на английском языке'
;

COMMENT ON COLUMN dictionary.bic.restriction_code
	IS 'Код ограничения, наложенного на участника | В соответствии с ED807 к одному БИК может быть несколько ограничений '
;

COMMENT ON COLUMN dictionary.bic.restriction_date
	IS 'Дата начала действия ограничения участника | В соответствии с ED807 к одному БИК может быть несколько ограничений'
;

COMMENT ON COLUMN dictionary.bic.swift_bic
	IS 'БИК (СВИФТ) | по справочнику СВИФТ, стандарт ИСО 9362'
;

COMMENT ON COLUMN dictionary.bic.default_swift_bic
	IS 'Признак использования БИК (СВИФТ), «по умолчанию»'
;

COMMENT ON COLUMN dictionary.bic.successor_bic
	IS 'БИК преемника | В соответствии с ED807 поле атрибут вводится при установке ограничения на счет (таблица bic_account)'
;

COMMENT ON COLUMN dictionary.bic.locality_type
	IS 'Тип населенного пункта | г.'
;

COMMENT ON COLUMN dictionary.bic.locality_name
	IS 'Наименование населенного пункта | Тверь'
;

COMMENT ON TABLE dictionary.bic_account
	IS 'Справочник счета БИК'
;

COMMENT ON COLUMN dictionary.bic_account.bic_code
	IS 'БИК'
;

COMMENT ON COLUMN dictionary.bic_account.account
	IS 'Номер счета'
;

COMMENT ON COLUMN dictionary.bic_account.regulation_type
	IS 'Тип счета в соответствии с нормативом'
;

COMMENT ON COLUMN dictionary.bic_account.cbr_bic
	IS 'БИК ПБР, обслуживающего счет участника перевода'
;

COMMENT ON COLUMN dictionary.bic_account.date_in
	IS 'Дата открытия счета'
;

COMMENT ON COLUMN dictionary.bic_account.date_out
	IS 'Дата исключения информации о счете участника'
;

COMMENT ON COLUMN dictionary.bic_account.restriction_code
	IS 'Код ограничения операций по счету | в соответствии с ED807 к одному счету может быть несколько ограничений'
;

COMMENT ON COLUMN dictionary.bic_account.restriction_date
	IS 'Дата начала действия Ограничения операций по счету | в соответствии с ED807 к одному счету может быть несколько ограничений'
;

COMMENT ON COLUMN dictionary.bic_account.is_active
	IS 'Статус актуальности данной записи'
;

COMMENT ON COLUMN dictionary.bic_account.status
	IS 'Статус счета из ED | ACAC'
;

COMMENT ON TABLE dictionary.bic_account_regulation_type
	IS 'Типы счетов в соответствии с нормативом'
;

COMMENT ON COLUMN dictionary.bic_account_regulation_type.regulation_type_id
	IS 'ID типа счета в соответствии с нормативом '
;

COMMENT ON COLUMN dictionary.bic_account_regulation_type.name
	IS 'Наименование типа счета в соответствии с нормативом '
;

COMMENT ON TABLE dictionary.bic_participant_type
	IS 'Типы участников перевода'
;

COMMENT ON COLUMN dictionary.bic_participant_type.participant_type_id
	IS 'ID типа участника перевода'
;

COMMENT ON COLUMN dictionary.bic_participant_type.name
	IS 'Наименование типа участника перевода'
;
