/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 18-янв-2023 16:04:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS dictionary.bic CASCADE
;

DROP TABLE IF EXISTS dictionary.bic_account CASCADE
;

DROP TABLE IF EXISTS dictionary.bic_account_regulation_type CASCADE
;

DROP TABLE IF EXISTS dictionary.bic_participant_type CASCADE
;

DROP TABLE IF EXISTS dictionary.country CASCADE
;

DROP TABLE IF EXISTS dictionary.currency CASCADE
;

DROP TABLE IF EXISTS dictionary.currency_quote CASCADE
;

DROP TABLE IF EXISTS dictionary.currency_quote_log CASCADE
;

DROP TABLE IF EXISTS dictionary.currency_type CASCADE
;

DROP TABLE IF EXISTS dictionary.holiday_country CASCADE
;

DROP TABLE IF EXISTS dictionary.holiday_currency CASCADE
;

DROP TABLE IF EXISTS dictionary.periods_signs_subject CASCADE
;

DROP TABLE IF EXISTS dictionary.subject CASCADE
;

DROP TABLE IF EXISTS dictionary.subject_name CASCADE
;

DROP TABLE IF EXISTS dictionary.subject_name_type CASCADE
;

DROP TABLE IF EXISTS dictionary.subject_type CASCADE
;

/* Drop Sequences */

DROP SEQUENCE  IF EXISTS  dictionary.asset_type_asset_type_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  dictionary.asset_types_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  dictionary.bic_account_bic_account_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  dictionary.currency_currency_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  dictionary.currency_quote_currency_quote_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  dictionary.currency_quote_log_currency_quote_log_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  dictionary.subject_name_subject_name_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  dictionary.subject_name_type_subject_name_type_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  dictionary.subject_subject_id_seq  CASCADE
;

DROP SEQUENCE  IF EXISTS  dictionary.subject_type_subject_type_id_seq  CASCADE
;

/* Create Sequences */

CREATE SEQUENCE dictionary.asset_type_asset_type_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;


CREATE SEQUENCE dictionary.asset_types_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;


CREATE SEQUENCE dictionary.bic_account_bic_account_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;


CREATE SEQUENCE dictionary.currency_currency_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;


CREATE SEQUENCE dictionary.currency_quote_currency_quote_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;


CREATE SEQUENCE dictionary.currency_quote_log_currency_quote_log_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;


CREATE SEQUENCE dictionary.subject_name_subject_name_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;


CREATE SEQUENCE dictionary.subject_name_type_subject_name_type_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;


CREATE SEQUENCE dictionary.subject_subject_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;


CREATE SEQUENCE dictionary.subject_type_subject_type_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
;


/* Create Tables */

CREATE TABLE dictionary.bic
(
	bic_code varchar(9) NOT NULL,	-- БИК
	is_active integer NOT NULL   DEFAULT 1,	-- Статус актуальности данной записи
	business_day date NULL,	-- Дата ОД, к которой относятся данные Справочника БИК | фактически дата последнего обновления
	version integer NULL,	--  Номер версии Справочника БИК в течение операционного дня
	participant_name varchar(160) NULL,	--  Наименование участника
	country_code varchar(3) NULL,	-- Код страны
	region_code integer NULL,	-- Код территории
	date_in date NULL,	-- Дата включения в состав участников перевода
	date_out date NULL,	-- Дата исключения информации об участнике
	participant_type_id integer NULL,	-- Тип участника перевода
	transfer_service integer NULL,	-- Доступные сервисы перевода денежных средств
	registration_number varchar(9) NULL,	--  Регистрационный порядковый номер
	parent_bic varchar(9) NULL,	-- БИК головной организации
	english_name varchar(140) NULL,	-- Наименование участника на английском языке
	restriction_code varchar(4) NULL,	-- Код ограничения, наложенного на участника | В соответствии с ED807 к одному БИК может быть несколько ограничений 
	restriction_date date NULL,	-- Дата начала действия ограничения участника | В соответствии с ED807 к одному БИК может быть несколько ограничений
	swift_bic varchar(11) NULL,	-- БИК (СВИФТ) | по справочнику СВИФТ, стандарт ИСО 9362
	default_swift_bic integer NULL,	-- Признак использования БИК (СВИФТ), «по умолчанию»
	successor_bic varchar(9) NULL,	-- БИК преемника | В соответствии с ED807 поле атрибут вводится при установке ограничения на счет (таблица bic_account)
	locality_type varchar(5) NULL,	-- Тип населенного пункта | г.
	locality_name varchar(25) NULL	-- Наименование населенного пункта | Тверь
)
;

CREATE TABLE dictionary.bic_account
(
	bic_code varchar(9) NOT NULL,	-- БИК
	account varchar(20) NOT NULL,	-- Номер счета
	regulation_type varchar(4) NULL,	-- Тип счета в соответствии с нормативом
	c_b_r_bic varchar(9) NULL,	-- БИК ПБР, обслуживающего счет участника перевода
	date_in date NULL,	-- Дата открытия счета
	date_out date NULL,	-- Дата исключения информации о счете участника
	restriction_code varchar(4) NULL,	-- Код ограничения операций по счету | в соответствии с ED807 к одному счету может быть несколько ограничений
	restriction_date date NULL,	-- Дата начала действия Ограничения операций по счету | в соответствии с ED807 к одному счету может быть несколько ограничений
	is_active integer NOT NULL,	-- Статус актуальности данной записи
	status varchar(4) NULL	-- Статус счета из ED | ACAC
)
;

CREATE TABLE dictionary.bic_account_regulation_type
(
	regulation_type_id char(4) NOT NULL,	-- ID типа счета в соответствии с нормативом 
	name varchar(100) NULL	-- Наименование типа счета в соответствии с нормативом 
)
;

CREATE TABLE dictionary.bic_participant_type
(
	participant_type_id integer NOT NULL,	-- ID типа участника перевода
	name varchar(100) NULL	-- Наименование типа участника перевода
)
;

CREATE TABLE dictionary.country
(
	country_id bigint NOT NULL,	-- Уникальный идентификатор записи | 204
	code char(3) NOT NULL,	-- Цифровой идентификатор страны | 705
	name_short varchar(100) NOT NULL,	-- Краткое наименование страны | СЛОВЕНИЯ
	name_full varchar(200) NULL,	-- Полное наименование страны | РЕСПУБЛИКА СЛОВЕНИЯ
	name_eng varchar(100) NULL,	-- Наименование страны латиницей | SLOVENIA
	code_alpha2 char(2) NOT NULL,	-- Буквенный 2x символьный идентификатор страны | SI
	code_alpha3 char(3) NOT NULL,	-- Буквенный 3x символьный идентификатор страны | SVN
	is_simple_tax boolean NULL,	-- Признак упрощенного налогообложения | FALSE
	is_div365 boolean NULL,	-- Дивиденды 365: True - да | TRUE
	is_act365 boolean NULL,	-- Акции 365: TRUE - да | TRUE
	day date NULL
)
;

CREATE TABLE dictionary.currency
(
	currency_id bigint NOT NULL,	-- Идентификатор | 9090
	currency_type_id bigint NOT NULL   DEFAULT 1,	-- Тип актива | 1
	code char(3) NOT NULL,	-- Уникальный цифровой код валюты | A90
	name varchar(100) NOT NULL,	-- Наименование валюты (драгметалла) на русском языке | Золото в унциях
	ascii_code char(3) NOT NULL	-- Уникальный буквенный код валюты | A90
)
;

CREATE TABLE dictionary.currency_quote
(
	currency_quote_id bigint NOT NULL,	-- Идентификатор
	asset_id bigint NOT NULL,	-- Идентификатор котируемой валюты
	quotation_date date NOT NULL,	-- Дата котировки
	currency_quantity integer NOT NULL,	-- Количество котируемой валюты
	base_currency_quantity numeric(28,4) NOT NULL,	-- Количество базовой валюты (рублей)
	quote_value numeric(28,4) NOT NULL,	-- Рассчитанное значение котировки на единицу котируемой валюты (base_curr_quantity/curr_quantity)
	quote_inst_id bigint NOT NULL,	-- Идентификатор котирующей орг-ии, например, ЦБ РФ (ссылка на справочник контрагентов)
	base_currency_id bigint NOT NULL,	-- Идентификатор базовой валюты
	direct_quote boolean NOT NULL	-- Признак прямой котировки
)
;

CREATE TABLE dictionary.currency_quote_log
(
	currency_quote_log_id bigint NOT NULL,	-- Идентификатор
	asset_id bigint NOT NULL,	-- Идентификатор котируемой валюты
	quotation_date date NOT NULL,	-- Дата котировки
	currency_quantity integer NOT NULL,	-- Количество котируемой валюты
	base_currency_quantity numeric(28,4) NOT NULL,	-- Количество базовой валюты (рублей)
	quote_value numeric(28,4) NOT NULL,	-- Рассчитанное значение котировки на единицу котируемой валюты (base_curr_quantity/curr_quantity)
	quote_inst_id bigint NOT NULL,	-- Идентификатор котирующей орг-ии, например, ЦБ РФ (ссылка на справочник контрагентов)
	base_currency_id bigint NOT NULL,	-- Идентификатор базовой валюты
	direct_quote boolean NOT NULL,	-- Признак прямой котировки
	user_id bigint NULL,	-- Ссылка на пользователя
	event_date timestamp without time zone NOT NULL,	-- Дата и время события
	event_description varchar(255) NULL	-- Описание события
)
;

CREATE TABLE dictionary.currency_type
(
	currency_type_id integer NOT NULL,	-- Идентификатор | 1
	name varchar(50) NOT NULL	-- Наименование типа | Валюта
)
;

CREATE TABLE dictionary.holiday_country
(
	day date NOT NULL,	-- Дата | 08.03.2022
	country_id bigint NOT NULL,	-- ID страны | 0
	type smallint NOT NULL,	-- Тип дня | 0 (0 - выходной/праздничный, 1 - рабочий)
	comment varchar(100) NULL	-- Комментарий | 8 марта
)
;

CREATE TABLE dictionary.holiday_currency
(
	day date NOT NULL,	-- Дата | 08.03.2022
	currency_id bigint NOT NULL,	--  Уникальный идентификатор валюты | 9090
	type smallint NOT NULL,	-- Тип дня | 0  (0 - выходной/праздничный, 1 - рабочий)
	comment varchar(100) NULL	-- Комментарий | 8 марта
)
;

CREATE TABLE dictionary.periods_signs_subject
(
	subject_id bigint NOT NULL,	-- ID субъекта (контрагента, эмитента) | Ссылка на SUBJECT
	signs_type smallint NOT NULL,	-- Тип взаимозависимости | 1 (1 - взаимозависимость, 2 - контроль сделок)
	begin_date date NOT NULL,	-- Начало периода контроля
	end_date date NULL	-- Конец периода контроля | 31/12/2022
)
;

CREATE TABLE dictionary.subject
(
	subject_id bigint NOT NULL,	-- Идентификатор
	subject_type_id integer NOT NULL,	-- Тип контрагента
	impact_type_id bigint NULL,	-- Тип вдействия
	is_res boolean NULL,	-- Резидент/нерезидент
	okpo varchar(10) NULL,	-- ОКПО
	birth_date date NULL,	-- Дата рождения
	tax_inspection_code varchar(15) NULL,	-- ИНН
	kpp varchar(9) NULL,	-- КПП
	confirmed integer NULL,	-- Подтвержденность изменения
	comments varchar(500) NULL,	-- Комментарии
	ogress_subject_code varchar(25) NULL,	-- Код субъекта в  OGRESS
	changed_user_id bigint NULL,	-- Код пользователя, осуществившего изменения (вставка/создание/удаление)
	is_pboul varchar(15) NULL,	-- Признак ПБОЮЛ
	ogress_subject_id bigint NULL,	-- ID субъекта в  OGRESS
	lang_country_id bigint NULL,	-- Код языка страны для отчетности
	ins_date timestamp without time zone NULL,	-- Дата вставки записи в таблицу
	supervised_by boolean NULL,	-- Курируемый
	ucr_subject_id bigint NULL,	-- MDM ID
	ucr_subject_code varchar(25) NULL,	-- MDM код
	confirmed_date date NULL	-- Дата конфирмирования
)
;

CREATE TABLE dictionary.subject_name
(
	subject_name_id integer NOT NULL,	-- Идентификатор
	subject_name_type_id bigint NOT NULL,	-- Id типа наименования
	subject_id bigint NOT NULL,	-- Id субъекта
	surname varchar(256) NULL,	-- Фамилия (Только для физических лиц)
	name varchar(256) NULL,	-- Имя (Только для физических лиц) Наименование ю.л.
	patronymic varchar(256) NULL	-- Отчество (Только для физических лиц)
)
;

CREATE TABLE dictionary.subject_name_type
(
	subject_name_type_id bigint NOT NULL,	-- Идентификатор
	name varchar(2000) NOT NULL,	-- Наименование
	short_name varchar(50) NULL	-- Краткое наименование наименования
)
;

CREATE TABLE dictionary.subject_type
(
	subject_type_id integer NOT NULL,	-- Идентификатор
	name varchar(20) NOT NULL	-- Наименование на русском языке
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE dictionary.bic ADD CONSTRAINT pk_dictionary_bic
	PRIMARY KEY (bic_code)
;

CREATE INDEX ixfk_dictionary_bic_transfer_participant_type ON dictionary.bic (participant_type_id ASC)
;

ALTER TABLE dictionary.bic_account ADD CONSTRAINT pk_dictionary_bic_account
	PRIMARY KEY (bic_code,account)
;

CREATE INDEX ixfk_dictionary_bic_account_bic_account_type ON dictionary.bic_account (regulation_type ASC)
;

ALTER TABLE dictionary.bic_account_regulation_type ADD CONSTRAINT pk_dictionary_bic_account_regulation_type
	PRIMARY KEY (regulation_type_id)
;

ALTER TABLE dictionary.bic_participant_type ADD CONSTRAINT pk_dictionary_bic_participant_type
	PRIMARY KEY (participant_type_id)
;

ALTER TABLE dictionary.country ADD CONSTRAINT pk_dictionary_country
	PRIMARY KEY (country_id)
;

ALTER TABLE dictionary.currency ADD CONSTRAINT pk_dictionary_currency
	PRIMARY KEY (currency_id)
;

ALTER TABLE dictionary.currency 
  ADD CONSTRAINT currency_ascii_code_key UNIQUE (ascii_code)
;

ALTER TABLE dictionary.currency 
  ADD CONSTRAINT currency_code_key UNIQUE (code)
;

ALTER TABLE dictionary.currency_quote ADD CONSTRAINT pk_dictionary_currency_quote
	PRIMARY KEY (currency_quote_id)
;

ALTER TABLE dictionary.currency_quote_log ADD CONSTRAINT pk_dictionary_currency_quote_log
	PRIMARY KEY (currency_quote_log_id)
;

ALTER TABLE dictionary.currency_type ADD CONSTRAINT pk_dictionary_currency_type
	PRIMARY KEY (currency_type_id)
;

ALTER TABLE dictionary.holiday_country ADD CONSTRAINT pk_dictionary_holiday_country
	PRIMARY KEY (country_id,day)
;

CREATE INDEX ixfk_dictionary_holiday_country_country ON dictionary.holiday_country (country_id ASC)
;

ALTER TABLE dictionary.holiday_currency ADD CONSTRAINT pk_dictionary_holiday_currency
	PRIMARY KEY (day,currency_id)
;

CREATE INDEX ixfk_dictionary_holiday_currency_currency ON dictionary.holiday_currency (currency_id ASC)
;

ALTER TABLE dictionary.periods_signs_subject ADD CONSTRAINT pk_dictionary_periods_signs_subject
	PRIMARY KEY (subject_id)
;

ALTER TABLE dictionary.subject ADD CONSTRAINT pk_dictionary_subject
	PRIMARY KEY (subject_id)
;

ALTER TABLE dictionary.subject_name ADD CONSTRAINT pk_dictionary_subject_name
	PRIMARY KEY (subject_name_id)
;

ALTER TABLE dictionary.subject_name_type ADD CONSTRAINT pk_dictionary_subject_name_type
	PRIMARY KEY (subject_name_type_id)
;

ALTER TABLE dictionary.subject_type ADD CONSTRAINT pk_dictionary_subject_type
	PRIMARY KEY (subject_type_id)
;

/* Create Foreign Key Constraints */

ALTER TABLE dictionary.bic ADD CONSTRAINT fk_dictionary_bic_participant_type_bic
	FOREIGN KEY (participant_type_id) REFERENCES dictionary.bic_participant_type (participant_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.bic_account ADD CONSTRAINT fk_dictionary_bic_account_bic_account_type
	FOREIGN KEY (regulation_type) REFERENCES dictionary.bic_account_regulation_type (regulation_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.bic_account ADD CONSTRAINT fk_dictionary_bic_account_bic
	FOREIGN KEY (bic_code) REFERENCES dictionary.bic (bic_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.currency ADD CONSTRAINT fk_dictionary_currency_currency_type
	FOREIGN KEY (currency_type_id) REFERENCES dictionary.currency_type (currency_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.currency_quote ADD CONSTRAINT fk_dictionary_currency_quote_asset_id_currency
	FOREIGN KEY (asset_id) REFERENCES dictionary.currency (currency_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.currency_quote ADD CONSTRAINT fk_dictionary_currency_quote_base_currency_id_currency
	FOREIGN KEY (base_currency_id) REFERENCES dictionary.currency (currency_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.currency_quote_log ADD CONSTRAINT fk_dictionary_currency_quote_log_base_currency_currency
	FOREIGN KEY (base_currency_id) REFERENCES dictionary.currency (currency_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.currency_quote_log ADD CONSTRAINT fk_dictionary_currency_quote_log_asset_currency
	FOREIGN KEY (asset_id) REFERENCES dictionary.currency (currency_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.holiday_country ADD CONSTRAINT fk_dictionary_holiday_country_country
	FOREIGN KEY (country_id) REFERENCES dictionary.country (country_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.holiday_currency ADD CONSTRAINT fk_dictionary_holiday_currency_currency
	FOREIGN KEY (currency_id) REFERENCES dictionary.currency (currency_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.subject ADD CONSTRAINT fk_dictionary_subject_subject_type
	FOREIGN KEY (subject_type_id) REFERENCES dictionary.subject_type (subject_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.subject_name ADD CONSTRAINT fk_dictionary_subject_name_subject
	FOREIGN KEY (subject_id) REFERENCES dictionary.subject (subject_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE dictionary.subject_name ADD CONSTRAINT fk_dictionary_subject_name_subject_name_type
	FOREIGN KEY (subject_name_type_id) REFERENCES dictionary.subject_name_type (subject_name_type_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE dictionary.bic
	IS 'Справочник БИК'
;

COMMENT ON COLUMN dictionary.bic.bic_code
	IS 'БИК'
;

COMMENT ON COLUMN dictionary.bic.is_active
	IS 'Статус актуальности данной записи'
;

COMMENT ON COLUMN dictionary.bic.business_day
	IS 'Дата ОД, к которой относятся данные Справочника БИК | фактически дата последнего обновления'
;

COMMENT ON COLUMN dictionary.bic.version
	IS ' Номер версии Справочника БИК в течение операционного дня'
;

COMMENT ON COLUMN dictionary.bic.participant_name
	IS ' Наименование участника'
;

COMMENT ON COLUMN dictionary.bic.country_code
	IS 'Код страны'
;

COMMENT ON COLUMN dictionary.bic.region_code
	IS 'Код территории'
;

COMMENT ON COLUMN dictionary.bic.date_in
	IS 'Дата включения в состав участников перевода'
;

COMMENT ON COLUMN dictionary.bic.date_out
	IS 'Дата исключения информации об участнике'
;

COMMENT ON COLUMN dictionary.bic.participant_type_id
	IS 'Тип участника перевода'
;

COMMENT ON COLUMN dictionary.bic.transfer_service
	IS 'Доступные сервисы перевода денежных средств'
;

COMMENT ON COLUMN dictionary.bic.registration_number
	IS ' Регистрационный порядковый номер'
;

COMMENT ON COLUMN dictionary.bic.parent_bic
	IS 'БИК головной организации'
;

COMMENT ON COLUMN dictionary.bic.english_name
	IS 'Наименование участника на английском языке'
;

COMMENT ON COLUMN dictionary.bic.restriction_code
	IS 'Код ограничения, наложенного на участника | В соответствии с ED807 к одному БИК может быть несколько ограничений '
;

COMMENT ON COLUMN dictionary.bic.restriction_date
	IS 'Дата начала действия ограничения участника | В соответствии с ED807 к одному БИК может быть несколько ограничений'
;

COMMENT ON COLUMN dictionary.bic.swift_bic
	IS 'БИК (СВИФТ) | по справочнику СВИФТ, стандарт ИСО 9362'
;

COMMENT ON COLUMN dictionary.bic.default_swift_bic
	IS 'Признак использования БИК (СВИФТ), «по умолчанию»'
;

COMMENT ON COLUMN dictionary.bic.successor_bic
	IS 'БИК преемника | В соответствии с ED807 поле атрибут вводится при установке ограничения на счет (таблица bic_account)'
;

COMMENT ON COLUMN dictionary.bic.locality_type
	IS 'Тип населенного пункта | г.'
;

COMMENT ON COLUMN dictionary.bic.locality_name
	IS 'Наименование населенного пункта | Тверь'
;

COMMENT ON TABLE dictionary.bic_account
	IS 'Справочник счета БИК'
;

COMMENT ON COLUMN dictionary.bic_account.bic_code
	IS 'БИК'
;

COMMENT ON COLUMN dictionary.bic_account.account
	IS 'Номер счета'
;

COMMENT ON COLUMN dictionary.bic_account.regulation_type
	IS 'Тип счета в соответствии с нормативом'
;

COMMENT ON COLUMN dictionary.bic_account.c_b_r_bic
	IS 'БИК ПБР, обслуживающего счет участника перевода'
;

COMMENT ON COLUMN dictionary.bic_account.date_in
	IS 'Дата открытия счета'
;

COMMENT ON COLUMN dictionary.bic_account.date_out
	IS 'Дата исключения информации о счете участника'
;

COMMENT ON COLUMN dictionary.bic_account.restriction_code
	IS 'Код ограничения операций по счету | в соответствии с ED807 к одному счету может быть несколько ограничений'
;

COMMENT ON COLUMN dictionary.bic_account.restriction_date
	IS 'Дата начала действия Ограничения операций по счету | в соответствии с ED807 к одному счету может быть несколько ограничений'
;

COMMENT ON COLUMN dictionary.bic_account.is_active
	IS 'Статус актуальности данной записи'
;

COMMENT ON COLUMN dictionary.bic_account.status
	IS 'Статус счета из ED | ACAC'
;

COMMENT ON TABLE dictionary.bic_account_regulation_type
	IS 'Типы счетов в соответствии с нормативом'
;

COMMENT ON COLUMN dictionary.bic_account_regulation_type.regulation_type_id
	IS 'ID типа счета в соответствии с нормативом '
;

COMMENT ON COLUMN dictionary.bic_account_regulation_type.name
	IS 'Наименование типа счета в соответствии с нормативом '
;

COMMENT ON TABLE dictionary.bic_participant_type
	IS 'Типы участников перевода'
;

COMMENT ON COLUMN dictionary.bic_participant_type.participant_type_id
	IS 'ID типа участника перевода'
;

COMMENT ON COLUMN dictionary.bic_participant_type.name
	IS 'Наименование типа участника перевода'
;

COMMENT ON TABLE dictionary.country
	IS 'Справочник стран'
;

COMMENT ON COLUMN dictionary.country.country_id
	IS 'Уникальный идентификатор записи | 204'
;

COMMENT ON COLUMN dictionary.country.code
	IS 'Цифровой идентификатор страны | 705'
;

COMMENT ON COLUMN dictionary.country.name_short
	IS 'Краткое наименование страны | СЛОВЕНИЯ'
;

COMMENT ON COLUMN dictionary.country.name_full
	IS 'Полное наименование страны | РЕСПУБЛИКА СЛОВЕНИЯ'
;

COMMENT ON COLUMN dictionary.country.name_eng
	IS 'Наименование страны латиницей | SLOVENIA'
;

COMMENT ON COLUMN dictionary.country.code_alpha2
	IS 'Буквенный 2x символьный идентификатор страны | SI'
;

COMMENT ON COLUMN dictionary.country.code_alpha3
	IS 'Буквенный 3x символьный идентификатор страны | SVN'
;

COMMENT ON COLUMN dictionary.country.is_simple_tax
	IS 'Признак упрощенного налогообложения | FALSE'
;

COMMENT ON COLUMN dictionary.country.is_div365
	IS 'Дивиденды 365: True - да | TRUE'
;

COMMENT ON COLUMN dictionary.country.is_act365
	IS 'Акции 365: TRUE - да | TRUE'
;

COMMENT ON TABLE dictionary.currency
	IS 'Справочник валют и драгоценных металлов'
;

COMMENT ON COLUMN dictionary.currency.currency_id
	IS 'Идентификатор | 9090'
;

COMMENT ON COLUMN dictionary.currency.currency_type_id
	IS 'Тип актива | 1'
;

COMMENT ON COLUMN dictionary.currency.code
	IS 'Уникальный цифровой код валюты | A90'
;

COMMENT ON COLUMN dictionary.currency.name
	IS 'Наименование валюты (драгметалла) на русском языке | Золото в унциях'
;

COMMENT ON COLUMN dictionary.currency.ascii_code
	IS 'Уникальный буквенный код валюты | A90'
;

COMMENT ON TABLE dictionary.currency_quote
	IS 'Справочник курсы валют и ДМ'
;

COMMENT ON COLUMN dictionary.currency_quote.currency_quote_id
	IS 'Идентификатор'
;

COMMENT ON COLUMN dictionary.currency_quote.asset_id
	IS 'Идентификатор котируемой валюты'
;

COMMENT ON COLUMN dictionary.currency_quote.quotation_date
	IS 'Дата котировки'
;

COMMENT ON COLUMN dictionary.currency_quote.currency_quantity
	IS 'Количество котируемой валюты'
;

COMMENT ON COLUMN dictionary.currency_quote.base_currency_quantity
	IS 'Количество базовой валюты (рублей)'
;

COMMENT ON COLUMN dictionary.currency_quote.quote_value
	IS 'Рассчитанное значение котировки на единицу котируемой валюты (base_curr_quantity/curr_quantity)'
;

COMMENT ON COLUMN dictionary.currency_quote.quote_inst_id
	IS 'Идентификатор котирующей орг-ии, например, ЦБ РФ (ссылка на справочник контрагентов)'
;

COMMENT ON COLUMN dictionary.currency_quote.base_currency_id
	IS 'Идентификатор базовой валюты'
;

COMMENT ON COLUMN dictionary.currency_quote.direct_quote
	IS 'Признак прямой котировки'
;

COMMENT ON TABLE dictionary.currency_quote_log
	IS 'Справочник курсы валют и ДМ'
;

COMMENT ON COLUMN dictionary.currency_quote_log.currency_quote_log_id
	IS 'Идентификатор'
;

COMMENT ON COLUMN dictionary.currency_quote_log.asset_id
	IS 'Идентификатор котируемой валюты'
;

COMMENT ON COLUMN dictionary.currency_quote_log.quotation_date
	IS 'Дата котировки'
;

COMMENT ON COLUMN dictionary.currency_quote_log.currency_quantity
	IS 'Количество котируемой валюты'
;

COMMENT ON COLUMN dictionary.currency_quote_log.base_currency_quantity
	IS 'Количество базовой валюты (рублей)'
;

COMMENT ON COLUMN dictionary.currency_quote_log.quote_value
	IS 'Рассчитанное значение котировки на единицу котируемой валюты (base_curr_quantity/curr_quantity)'
;

COMMENT ON COLUMN dictionary.currency_quote_log.quote_inst_id
	IS 'Идентификатор котирующей орг-ии, например, ЦБ РФ (ссылка на справочник контрагентов)'
;

COMMENT ON COLUMN dictionary.currency_quote_log.base_currency_id
	IS 'Идентификатор базовой валюты'
;

COMMENT ON COLUMN dictionary.currency_quote_log.direct_quote
	IS 'Признак прямой котировки'
;

COMMENT ON COLUMN dictionary.currency_quote_log.user_id
	IS 'Ссылка на пользователя'
;

COMMENT ON COLUMN dictionary.currency_quote_log.event_date
	IS 'Дата и время события'
;

COMMENT ON COLUMN dictionary.currency_quote_log.event_description
	IS 'Описание события'
;

COMMENT ON TABLE dictionary.currency_type
	IS 'Типы активов (валюты и ДМ)'
;

COMMENT ON COLUMN dictionary.currency_type.currency_type_id
	IS 'Идентификатор | 1'
;

COMMENT ON COLUMN dictionary.currency_type.name
	IS 'Наименование типа | Валюта'
;

COMMENT ON TABLE dictionary.holiday_country
	IS 'Производственный календарь стран'
;

COMMENT ON COLUMN dictionary.holiday_country.day
	IS 'Дата | 08.03.2022'
;

COMMENT ON COLUMN dictionary.holiday_country.country_id
	IS 'ID страны | 0'
;

COMMENT ON COLUMN dictionary.holiday_country.type
	IS 'Тип дня | 0 (0 - выходной/праздничный, 1 - рабочий)'
;

COMMENT ON COLUMN dictionary.holiday_country.comment
	IS 'Комментарий | 8 марта'
;

COMMENT ON TABLE dictionary.holiday_currency
	IS 'Производственный календарь валют'
;

COMMENT ON COLUMN dictionary.holiday_currency.day
	IS 'Дата | 08.03.2022'
;

COMMENT ON COLUMN dictionary.holiday_currency.currency_id
	IS ' Уникальный идентификатор валюты | 9090'
;

COMMENT ON COLUMN dictionary.holiday_currency.type
	IS 'Тип дня | 0  (0 - выходной/праздничный, 1 - рабочий)'
;

COMMENT ON COLUMN dictionary.holiday_currency.comment
	IS 'Комментарий | 8 марта'
;

COMMENT ON TABLE dictionary.periods_signs_subject
	IS 'Взаимозависимые лица'
;

COMMENT ON COLUMN dictionary.periods_signs_subject.subject_id
	IS 'ID субъекта (контрагента, эмитента) | Ссылка на SUBJECT'
;

COMMENT ON COLUMN dictionary.periods_signs_subject.signs_type
	IS 'Тип взаимозависимости | 1 (1 - взаимозависимость, 2 - контроль сделок)'
;

COMMENT ON COLUMN dictionary.periods_signs_subject.begin_date
	IS 'Начало периода контроля'
;

COMMENT ON COLUMN dictionary.periods_signs_subject.end_date
	IS 'Конец периода контроля | 31/12/2022'
;

COMMENT ON TABLE dictionary.subject
	IS 'Справочник контрагентов'
;

COMMENT ON COLUMN dictionary.subject.subject_id
	IS 'Идентификатор'
;

COMMENT ON COLUMN dictionary.subject.subject_type_id
	IS 'Тип контрагента'
;

COMMENT ON COLUMN dictionary.subject.impact_type_id
	IS 'Тип вдействия'
;

COMMENT ON COLUMN dictionary.subject.is_res
	IS 'Резидент/нерезидент'
;

COMMENT ON COLUMN dictionary.subject.okpo
	IS 'ОКПО'
;

COMMENT ON COLUMN dictionary.subject.birth_date
	IS 'Дата рождения'
;

COMMENT ON COLUMN dictionary.subject.tax_inspection_code
	IS 'ИНН'
;

COMMENT ON COLUMN dictionary.subject.kpp
	IS 'КПП'
;

COMMENT ON COLUMN dictionary.subject.confirmed
	IS 'Подтвержденность изменения'
;

COMMENT ON COLUMN dictionary.subject.comments
	IS 'Комментарии'
;

COMMENT ON COLUMN dictionary.subject.ogress_subject_code
	IS 'Код субъекта в  OGRESS'
;

COMMENT ON COLUMN dictionary.subject.changed_user_id
	IS 'Код пользователя, осуществившего изменения (вставка/создание/удаление)'
;

COMMENT ON COLUMN dictionary.subject.is_pboul
	IS 'Признак ПБОЮЛ'
;

COMMENT ON COLUMN dictionary.subject.ogress_subject_id
	IS 'ID субъекта в  OGRESS'
;

COMMENT ON COLUMN dictionary.subject.lang_country_id
	IS 'Код языка страны для отчетности'
;

COMMENT ON COLUMN dictionary.subject.ins_date
	IS 'Дата вставки записи в таблицу'
;

COMMENT ON COLUMN dictionary.subject.supervised_by
	IS 'Курируемый'
;

COMMENT ON COLUMN dictionary.subject.ucr_subject_id
	IS 'MDM ID'
;

COMMENT ON COLUMN dictionary.subject.ucr_subject_code
	IS 'MDM код'
;

COMMENT ON COLUMN dictionary.subject.confirmed_date
	IS 'Дата конфирмирования'
;

COMMENT ON TABLE dictionary.subject_name
	IS 'Справочник наименований'
;

COMMENT ON COLUMN dictionary.subject_name.subject_name_id
	IS 'Идентификатор'
;

COMMENT ON COLUMN dictionary.subject_name.subject_name_type_id
	IS 'Id типа наименования'
;

COMMENT ON COLUMN dictionary.subject_name.subject_id
	IS 'Id субъекта'
;

COMMENT ON COLUMN dictionary.subject_name.surname
	IS 'Фамилия (Только для физических лиц)'
;

COMMENT ON COLUMN dictionary.subject_name.name
	IS 'Имя (Только для физических лиц) Наименование ю.л.'
;

COMMENT ON COLUMN dictionary.subject_name.patronymic
	IS 'Отчество (Только для физических лиц)'
;

COMMENT ON TABLE dictionary.subject_name_type
	IS 'Справочник тип контрагента'
;

COMMENT ON COLUMN dictionary.subject_name_type.subject_name_type_id
	IS 'Идентификатор'
;

COMMENT ON COLUMN dictionary.subject_name_type.name
	IS 'Наименование'
;

COMMENT ON COLUMN dictionary.subject_name_type.short_name
	IS 'Краткое наименование наименования'
;

COMMENT ON TABLE dictionary.subject_type
	IS 'Справочник тип контрагента'
;

COMMENT ON COLUMN dictionary.subject_type.subject_type_id
	IS 'Идентификатор'
;

COMMENT ON COLUMN dictionary.subject_type.name
	IS 'Наименование на русском языке'
;
